[package]
name = "digfill"
version = "0.1.0"
authors = ["Reconcyl <22424430+Reconcyl@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
termion = "1.5.5"
