[package]
name = "lazyk_minifier_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = { package = "imbl", version = "3.0.0" }
indexmap = "2.2.6"
